# Use an official Node.js runtime as the base image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project to the working directory
COPY . .


# Expose the port that the app will run on
EXPOSE 5173

# Set the command to start the app
CMD ["npm", "run", "dev"]
